### ISSUE TITLE
Possible issues: Error message in structured data tool

### ISSUE THREAD

**Issue by prasantrai** [shivaacharjee/sailenseo#1]
Getting `Failed to normalise the rating value.` error in Google structured data testing tool. Getting this error when Rich snippet selected item is Product. For more detail refer to this URL:

https://search.google.com/structured-data/testing-tool#url=http%3A%2F%2F128.199.211.55%2Findex.php%2F2016%2F06%2F11%2Fgoogle%2F

**Comment by shivaacharjee** [comment]
Default rating was set to null. fixed
